version: '3.8'

services:
  # BEGIN es-db
  es-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: es-db
    volumes:
      - ${ES_DATA:-./es-data}:/usr/share/elasticsearch/data
    env_file:
      - ./.env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
    deploy:
      resources:
        limits:
          memory: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network
  # END es-db

networks:
  app-network:
    external: true
